apiVersion: v1
kind: Namespace
metadata:
  name: sales-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-deploy
  namespace: sales-system
spec:
  selector:
    matchLabels:
      app: sales
  template:
    metadata:
      labels:
        app: sales
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: init-migrate
          image: sales-api-image
          command: ["./admin"]
      containers:
        - name: zipkin
          image: openzipkin
          ports:
            - name: zipkin
              containerPort: 9411
        - name: sales-api
          image: sales-api-image
          ports:
            - name: sales-api
              containerPort: 3000
            - name: sales-api-debug
              containerPort: 4000
          readinessProbe: # readiness probes mark the service available to accept traffic
            httpGet:
             path: /debug/readiness
             port: 4000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          livenessProbe: # liveness probes mark the service alive or dead (to be restarted)
            httpGet:
              path: /debug/liveness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: sales-svc
  namespace: sales-system
spec:
  type: ClusterIP
  selector:
    app: sales
  ports:
    - name: sales-api
      port: 3000
      targetPort: sales-api
    - name: sales-api-debug
      port: 4000
      targetPort: sales-api-debug
    - name: zipkin
      port: 9411
      targetPort: zipkin
---
apiVersion: v1
kind: Service
metadata:
  name: sales-node-port-svc
  namespace: sales-system
spec:
  type: NodePort
  selector:
    app: sales
  ports:
    - name: 30190-3000
      nodePort: 30190
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: 30191-4000
      nodePort: 30191
      port: 4000
      protocol: TCP
      targetPort: 4000
    - name: 30192-9411
      nodePort: 30192
      port: 9411
      protocol: TCP
